on: 
 push
name: Jira Issue comment Updation Demo
jobs:
  jiraIssueUpdation:
    name: Jira Issue Updation Demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Login
      uses: atlassian/gajira-login@master
      env:
       JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
       JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
       JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
     
     
   	
    - name: Updating JIRA issue comment
      uses: atlassian/gajira-comment@master
      with:
      issue: GJD-2
      comment: ${{ github.event.pusher.name }} pushed to repository:${{ github.event.repository.full_name }}
